name: OWASP ZAP API Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_api_scan:
    runs-on: ubuntu-latest
    name: Scan ${{ matrix.environment.name }} API
    permissions:
      contents: read
      issues: write

    strategy:
      fail-fast: false
      matrix:
        environment:
          - name: 'Insecure'
            path_prefix: 'insecure'
            url: 'https://owasp-sec-bank-insecure.onrender.com'
          - name: 'Secure'
            path_prefix: 'secure'
            url: 'https://owasp-sec-bank-secure.onrender.com'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix Permissions
        run: chmod -R 777 .

      - name: Fetch JWT Token
        run: node ${{ matrix.environment.path_prefix }}/backend/scripts/get_token.js

      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          format: openapi
          target: '${{ matrix.environment.path_prefix }}/backend/swagger.json'
          target_url: '${{ matrix.environment.url }}'
          fail_action: false
          allow_issue_writing: false
        env:
          ZAP_AUTH_HEADER: "Authorization"
          ZAP_AUTH_HEADER_VALUE: ${{ env.ZAP_AUTH_HEADER_VALUE }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-${{ matrix.environment.name }}-Report
          path: report_html.html
